# 一定要注意缩进
server:
  port: 8081
  servlet:
    context-path: /

# 自定义
student:
  s_name: 封装配置信息
  s_age: 15

name: 测试yml文件属性
number: 123
content: "name: ${name}, number: ${number}"
# 自定义 end
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    cache: false
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver # 驱动
  jackson:
    serialization:
      indent-output: true
  #hibernate配置
  jpa:
    show-sql: true  # 日志中显示sql语句
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

    hibernate:
      # Hibernate ddl auto (create, create-drop, update)  
      ddl-auto: update  # 新增数据库链接必备的参数 自动更新
      naming:
        physical-strategy: com.wq.springboot.config.CustomPhysicalNamingStrategy
        # org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #hibernate配置 end
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.wq.springboot.entity
  configuration:
    # 控制台打印查询语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
