# 一定要注意缩进
server:
  port: 8081
  servlet:
    context-path: /

# 自定义
student:
  s_name: 封装配置信息
  s_age: 15

name: 测试yml文件属性
number: 123
content: "name: ${name}, number: ${number}"
# 自定义 end
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://www.huakevip.com:3306/spring_mybatis_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: aq2222222
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update  # 新增数据库链接必备的参数
      naming:
        physical-strategy: com.wq.springboot.CustomPhysicalNamingStrategy
        # org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.wq.springboot.entity
  configuration:
    # 控制台打印查询语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl